all:
	javac -cp rd881.jar *.java

run:
	java -jar rd881.jar

clean:
	rm AgentAction.class BaseLearningAgent.class CellContents.class BigBrainersAgent.class LearnerOne\$QMap.class BigBrainersFactory.class LearningAgentSensorSystem.class performance.out robotdefense.log StateVector.class